/**
 * Small WebP paths for grid / WebGL, generated by `npm run generate:thumbs`.
 * Full JPEGs stay on `imagePath` for detail views.
 */
export function tarotCardThumbnailPath(imagePath: string): string {
  const m = imagePath.match(/^(\/card-images\/)([^/]+)\.jpe?g$/i);
  if (!m) return imagePath;
  return `${m[1]}thumbs/${m[2]}.webp`;
}
